apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-prod
resources:
  - ../base/podinfo
patchesStrategicMerge:
  - podinfo-values.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: podinfo-prod
      namespace: podinfo-prod
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true